version: "3.3"

services:
  influx:
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_USER_PASSWORD=root
    ports:
      - "8086:8086"
      - "9999:9999"
    image: "quay.io/influxdb/influxdb:2.0.0-rc"
    volumes: 
      - "./influx-command.sh:/influx-command.sh"
    container_name: "influx"
    command: 
      - /influx-command.sh
    
  influx-client:
    build: ./influx-client
    container_name: "influx-client"
    depends_on: 
      - influx
      - portainer

  portainer:
    ports:
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    image: "portainer/portainer"
    container_name: "portainer"