version: "3.3"

services:
  influx:
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_USER_PASSWORD=root
    ports:
      - "8086:8086"
      - "9999:9999"
    image: "quay.io/influxdb/influxdb:2.0.0-rc"
    volumes: 
      - "./influx-start.sh:/influx-start.sh"
    container_name: "influx"
    command: 
      - /influx-start.sh
    
  influx-client:
    build: ./influx-client
    container_name: "influx-client"
    volumes: 
      - "./influx-client/client-start.sh:/client-start.sh"
    depends_on: 
      - influx
      - portainer

  portainer:
    ports:
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    image: "portainer/portainer"
    container_name: "portainer"

  #grafana:
  #  ports:
  #    - 3000:3000
  #  image: grafana/grafana
  #  container_name: grafana
  #  logging:
  #    driver: "none"
    